"""Tool response contracts — Python mirror of `lib/contracts/api/agent/*.ts`.

We validate the `data` payload from each Next.js tool call before handing it
to the planner LLM. Catches drift early (TS contract changed, Python registry
not updated) and surfaces structured errors instead of letting the LLM work
on `dict` soup.

Status (Fase 1):
- agenda (PILOT): full coverage (11 actions)
- other domains: not yet ported — `get_response_model()` returns None for them,
  validation falls back to passthrough (no-op).

Roadmap: as each domain's TS contract stabilizes, mirror its Pydantic models
under `agent/app/tools/contracts/{domain}.py` and register it below.

Generated by hand from `lib/contracts/api/agent/agenda.ts`. Eventually we'll
codegen this from Zod via `pnpm contracts:py`.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from . import agenda as _agenda
from . import orders as _orders
from . import clients as _clients
from . import sales as _sales


def _split_tool_name(tool_name: str) -> tuple[str, str]:
    """`agenda_book` -> (`agenda`, `book`). Mirrors client._split_action."""
    namespace, _, action = tool_name.partition("_")
    rest = tool_name[len(namespace) + 1 :] if namespace else action
    return namespace, rest


# Registry: (domain, action) -> Pydantic model used to validate `data`.
# Add entries as you port domains. Missing entries fall through (no validation).
_AGENDA_MODELS: dict[str, type[BaseModel] | None] = {
    "list_services":      _agenda.ListServicesResponse,
    "list_professionals": _agenda.ListProfessionalsResponse,
    "check_availability": _agenda.CheckAvailabilityData,
    "get_next_available": _agenda.GetNextAvailableData,
    "book":               _agenda.BookData,
    "list_by_client":     _agenda.ListByClientResponse,
    "list_upcoming":      _agenda.ListUpcomingResponse,
    "list_today":         _agenda.ListTodayResponse,
    "get":                None,  # nullable response — keep loose for now
    "update":             _agenda.AppointmentShort,
    "cancel":             _agenda.CancelData,
}

_ORDERS_MODELS: dict[str, type[BaseModel] | None] = {
    "create":         _orders.OrdersCreateData,
    "get":            None,
    "list_by_client": _orders.OrdersListByClientResponse,
    "update_status":  _orders.OrdersUpdateStatusData,
    "update_items":   _orders.OrdersUpdateItemsData,
    "cancel":         _orders.OrdersCancelData,
    "list_recent":    _orders.OrdersListRecentResponse,
}

_CLIENTS_MODELS: dict[str, type[BaseModel] | None] = {
    "lookup_by_phone":  None,                              # nullable
    "create":           _clients.ClientShape,
    "get":              None,                              # nullable
    "update":           _clients.ClientShape,
    "update_address":   _clients.ClientsUpdateAddressData,
    "get_full_history": _clients.ClientsGetFullHistoryData,
}

_SALES_MODELS: dict[str, type[BaseModel] | None] = {
    "list":           _sales.SalesListResponse,
    "get":            None,                                # nullable
    "list_by_client": _sales.SalesListByClientResponse,
    "create":         _sales.SaleShape,
    "cancel":         _sales.SaleShape,
    "summary_today":  _sales.SalesSummaryTodayData,
}


def get_response_model(tool_name: str) -> type[BaseModel] | None:
    """Lookup the Pydantic model for a given tool. None = no validation."""
    domain, action = _split_tool_name(tool_name)
    if domain == "agenda":
        return _AGENDA_MODELS.get(action)
    if domain == "orders":
        return _ORDERS_MODELS.get(action)
    if domain == "clients":
        return _CLIENTS_MODELS.get(action)
    if domain == "sales":
        return _SALES_MODELS.get(action)
    # Other domains: not yet ported. Add when contracts stabilize.
    return None


def validate_response_data(tool_name: str, data: Any) -> Any:
    """Validate `data` against the registered model. Returns parsed dict.

    On validation failure, raises pydantic.ValidationError. The executor catches
    it and surfaces a clean ToolError to the LLM so it can retry/adjust.
    """
    model = get_response_model(tool_name)
    if model is None:
        return data
    # Lists and nullable singletons are handled by their model's root type
    # via `RootModel` (see agenda.py). For plain BaseModel, pass dict.
    parsed = model.model_validate(data)
    return parsed.model_dump(mode="json", exclude_none=False)
