"""Tool response contracts — Python mirror of `lib/contracts/api/agent/*.ts`.

We validate the `data` payload from each Next.js tool call before handing it
to the planner LLM. Catches drift early (TS contract changed, Python registry
not updated) and surfaces structured errors instead of letting the LLM work
on `dict` soup.

Status (M11.1b, 08/09/2026): all 20 domains + send-interactive now have
Pydantic coverage. Only `agenda` was hand-verified end-to-end originally
(Fase 1 pilot); the other 16 domains + send-interactive were ported in this
same session by mirroring each domain's already-audited TS contract
(`lib/contracts/api/agent/{domain}.ts`, fixed during M11 on 07/09/2026) —
faithful translation, not independent re-derivation. Each new file was
verified to import cleanly and round-trip sample payloads before being wired
in here.

Two tool-name quirks worth knowing (both confirmed against
`agent/app/tools/client.py`'s TOOL_ENDPOINTS, not assumed):
  - `purchase-notes_*` tools use a literal HYPHEN in the tool name (not an
    underscore) — `_split_tool_name` only splits on the first `_`, so the
    namespace correctly resolves to `"purchase-notes"` (with hyphen). The
    Python *module* is `purchase_notes.py` (hyphens aren't valid in Python
    module names) — module filename and registry key are different strings,
    don't conflate them.
  - `conversation_send_interactive` is the ONLY tool whose namespace (per
    `_split_tool_name`) is `"conversation"` (singular) — not `"conversations"`
    (the real, separate domain) and not `"send-interactive"` (the TS
    `AGENT_TOOL_DOMAINS` key). This one tool has its own special-cased
    dispatch branch below.

Generated by hand from the TS contracts. Eventually we'll codegen this from
Zod via `pnpm contracts:py`.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from . import agenda as _agenda
from . import orders as _orders
from . import clients as _clients
from . import sales as _sales
from . import financial as _financial
from . import catalog as _catalog
from . import crm as _crm
from . import inventory as _inventory
from . import business as _business
from . import memory as _memory
from . import services as _services
from . import team as _team
from . import knowledge as _knowledge
from . import conversations as _conversations
from . import notes as _notes
from . import purchase_notes as _purchase_notes
from . import suppliers as _suppliers
from . import kanban as _kanban
from . import fiscal as _fiscal
from . import reports as _reports
from . import send_interactive as _send_interactive


def _split_tool_name(tool_name: str) -> tuple[str, str]:
    """`agenda_book` -> (`agenda`, `book`). Mirrors client._split_action."""
    namespace, _, action = tool_name.partition("_")
    rest = tool_name[len(namespace) + 1 :] if namespace else action
    return namespace, rest


# Registry: (domain, action) -> Pydantic model used to validate `data`.
# Add entries as you port domains. Missing entries fall through (no validation).
_AGENDA_MODELS: dict[str, type[BaseModel] | None] = {
    "list_services":      _agenda.ListServicesResponse,
    "list_professionals": _agenda.ListProfessionalsResponse,
    "check_availability": _agenda.CheckAvailabilityData,
    "get_next_available": _agenda.GetNextAvailableData,
    "book":               _agenda.BookData,
    "list_by_client":     _agenda.ListByClientResponse,
    "list_upcoming":      _agenda.ListUpcomingResponse,
    "list_today":         _agenda.ListTodayResponse,
    "get":                None,  # nullable response — keep loose for now
    "update":             _agenda.AppointmentShort,
    "cancel":             _agenda.CancelData,
}

_ORDERS_MODELS: dict[str, type[BaseModel] | None] = {
    "create":         _orders.OrdersCreateData,
    "get":            None,
    "list_by_client": _orders.OrdersListByClientResponse,
    "update_status":  _orders.OrdersUpdateStatusData,
    "update_items":   _orders.OrdersUpdateItemsData,
    "cancel":         _orders.OrdersCancelData,
    "list_recent":    _orders.OrdersListRecentResponse,
}

_CLIENTS_MODELS: dict[str, type[BaseModel] | None] = {
    "lookup_by_phone":  None,                              # nullable
    "create":           _clients.ClientShape,
    "get":              None,                              # nullable
    "update":           _clients.ClientShape,
    "update_address":   _clients.ClientsUpdateAddressData,
    "get_full_history": _clients.ClientsGetFullHistoryData,
}

_SALES_MODELS: dict[str, type[BaseModel] | None] = {
    "list":           _sales.SalesListResponse,
    "get":            None,                                # nullable
    "list_by_client": _sales.SalesListByClientResponse,
    "create":         _sales.SaleShape,
    "cancel":         _sales.SaleShape,
    "summary_today":  _sales.SalesSummaryTodayData,
}

_FINANCIAL_MODELS: dict[str, type[BaseModel] | None] = {
    "list":               _financial.FinancialListResponse,
    "get":                None,                            # nullable
    "create_receivable":  _financial.FinancialCreateTxResponse,
    "create_payable":     _financial.FinancialCreateTxResponse,
    "mark_paid":          _financial.TransactionShape,
    "cancel":             _financial.TransactionShape,
    "summary_today":      _financial.FinancialSummaryTodayData,
    "summary_month":      _financial.FinancialSummaryMonthData,
}

_CATALOG_MODELS: dict[str, type[BaseModel] | None] = {
    "list_menu":       _catalog.CatalogListMenuData,
    "search":          _catalog.CatalogSearchData,
    "get":             None,                               # nullable
    "list_categories": _catalog.CatalogListCategoriesData,
}

_CRM_MODELS: dict[str, type[BaseModel] | None] = {
    "list_contacts":     _crm.CRMListContactsResponse,
    "search_contacts":   _crm.CRMSearchContactsResponse,
    "list_deals":        _crm.CRMListDealsResponse,
    "search_deals":      _crm.CRMSearchDealsResponse,
    "get_deal":          None,                             # nullable
    "create_deal":       _crm.DealShape,
    "update_deal_stage": _crm.DealShape,
    "close_deal":        _crm.DealShape,
    "list_activities":   _crm.CRMListActivitiesResponse,
    "log_activity":      _crm.ActivityShape,
    "list_segments":     _crm.CRMListSegmentsResponse,
    "segment_query":     _crm.CRMSegmentQueryData,
}

_INVENTORY_MODELS: dict[str, type[BaseModel] | None] = {
    "list":             _inventory.InventoryListResponse,
    "get":              None,                              # nullable
    "search":           _inventory.InventorySearchResponse,
    "create":           _inventory.ProductShape,
    "update":           _inventory.ProductShape,
    "adjust_stock":     _inventory.InventoryAdjustStockData,
    "list_low_stock":   _inventory.InventoryListLowStockResponse,
    "set_active":       _inventory.ProductShape,
    "set_out_of_stock": _inventory.ProductShape,
}

_BUSINESS_MODELS: dict[str, type[BaseModel] | None] = {
    "get_context": _business.BusinessGetContextData,
}

_MEMORY_MODELS: dict[str, type[BaseModel] | None] = {
    "recall":   _memory.MemoryRecallData,
    "remember": _memory.MemoryFact,     # MemoryRememberDataSchema == FactSchema in TS
    "forget":   _memory.MemoryForgetData,
    "clear":    _memory.MemoryClearData,
}

_SERVICES_MODELS: dict[str, type[BaseModel] | None] = {
    "list":         _services.ServicesListResponse,
    "get":          None,                                  # nullable
    "search":       _services.ServicesSearchResponse,
    "create":       _services.ServiceShape,
    "update":       _services.ServiceShape,
    "set_active":   _services.ServiceShape,
    "import_grade": _services.ServicesImportGradeData,
}

_TEAM_MODELS: dict[str, type[BaseModel] | None] = {
    "list_sectors":   _team.TeamListSectorsResponse,
    "list_members":   _team.TeamListMembersResponse,
    "get_member":     None,                                # nullable
    "capacity_today": _team.TeamCapacityTodayResponse,
}

_KNOWLEDGE_MODELS: dict[str, type[BaseModel] | None] = {
    "search": _knowledge.KnowledgeSearchData,
}

_CONVERSATIONS_MODELS: dict[str, type[BaseModel] | None] = {
    "list":             _conversations.ConversationsListResponse,
    "get":              None,                              # nullable
    "list_messages":    _conversations.ConversationsListMessagesResponse,
    "set_label":        _conversations.ConvShape,
    "set_priority":     _conversations.ConvShape,
    "set_status":       _conversations.ConvShape,
    "list_snippets":    _conversations.ConversationsListSnippetsResponse,
    "search_snippets":  _conversations.ConversationsSearchSnippetsResponse,
}

_NOTES_MODELS: dict[str, type[BaseModel] | None] = {
    "list":   _notes.NotesListResponse,
    "get":    None,                                        # nullable
    "create": _notes.NoteShape,
    "update": _notes.NoteShape,
    "delete": _notes.NotesDeleteData,
    "search": _notes.NotesSearchResponse,
}

# Registry KEY is "purchase-notes" (hyphen) — matches the tool-name namespace,
# NOT the Python module filename (purchase_notes.py, underscore required).
_PURCHASE_NOTES_MODELS: dict[str, type[BaseModel] | None] = {
    "list":           _purchase_notes.PurchaseNotesListResponse,
    "get":            None,                                # nullable
    "match_products": _purchase_notes.PurchaseNotesMatchProductsData,
    "apply_to_stock": _purchase_notes.PurchaseNotesApplyToStockData,
    "list_unmatched": _purchase_notes.PurchaseNotesListUnmatchedResponse,
    "reverse_stock":  _purchase_notes.PurchaseNotesReverseStockData,
    "link_financial": _purchase_notes.PurchaseNotesLinkFinancialData,
}

_SUPPLIERS_MODELS: dict[str, type[BaseModel] | None] = {
    "list":         _suppliers.SuppliersListResponse,
    "get":          None,                                  # nullable
    "create":       _suppliers.SupplierShape,
    "update":       _suppliers.SupplierShape,
    "find_by_cnpj": None,                                  # nullable
    "search":       _suppliers.SuppliersSearchResponse,
}

_KANBAN_MODELS: dict[str, type[BaseModel] | None] = {
    "list_boards":  _kanban.KanbanListBoardsResponse,
    "get_board":    None,                                  # nullable
    "list_cards":   _kanban.KanbanListCardsResponse,
    "search_cards": _kanban.KanbanSearchCardsResponse,
    "get_card":     None,                                  # nullable
    "create_card":  _kanban.CardShape,
    "move_card":    _kanban.CardShape,
    "update_card":  _kanban.CardShape,
    "assign":       _kanban.CardShape,
    "add_comment":  _kanban.Comment,
    "archive_card": _kanban.KanbanArchiveCardData,
}

_FISCAL_MODELS: dict[str, type[BaseModel] | None] = {
    "get":          None,                                  # nullable
    "query_status": None,                                  # nullable
    "list":         _fiscal.FiscalListResponse,
    "emit":         _fiscal.FiscalEmitData,
    "cancel":       _fiscal.FiscalCancelData,
}

_REPORTS_MODELS: dict[str, type[BaseModel] | None] = {
    "revenue_by_period":            _reports.RevenueByPeriodData,
    "sales_by_product":             _reports.SalesByProductData,
    "appointments_by_professional": _reports.AppointmentsByProfessionalData,
    "top_clients":                  _reports.TopClientsData,
}

# `conversation_send_interactive` is the only tool in this namespace — see
# module docstring for why the domain string is "conversation", not
# "send-interactive" or "conversations".
_SEND_INTERACTIVE_MODELS: dict[str, type[BaseModel] | None] = {
    "send_interactive": _send_interactive.SendInteractiveData,
}

_REGISTRY: dict[str, dict[str, type[BaseModel] | None]] = {
    "agenda": _AGENDA_MODELS,
    "orders": _ORDERS_MODELS,
    "clients": _CLIENTS_MODELS,
    "sales": _SALES_MODELS,
    "financial": _FINANCIAL_MODELS,
    "catalog": _CATALOG_MODELS,
    "crm": _CRM_MODELS,
    "inventory": _INVENTORY_MODELS,
    "business": _BUSINESS_MODELS,
    "memory": _MEMORY_MODELS,
    "services": _SERVICES_MODELS,
    "team": _TEAM_MODELS,
    "knowledge": _KNOWLEDGE_MODELS,
    "conversations": _CONVERSATIONS_MODELS,
    "notes": _NOTES_MODELS,
    "purchase-notes": _PURCHASE_NOTES_MODELS,
    "suppliers": _SUPPLIERS_MODELS,
    "kanban": _KANBAN_MODELS,
    "fiscal": _FISCAL_MODELS,
    "reports": _REPORTS_MODELS,
    "conversation": _SEND_INTERACTIVE_MODELS,  # conversation_send_interactive quirk
}


def get_response_model(tool_name: str) -> type[BaseModel] | None:
    """Lookup the Pydantic model for a given tool. None = no validation."""
    domain, action = _split_tool_name(tool_name)
    domain_models = _REGISTRY.get(domain)
    if domain_models is None:
        return None
    return domain_models.get(action)


def validate_response_data(tool_name: str, data: Any) -> Any:
    """Validate `data` against the registered model. Returns parsed dict.

    On validation failure, raises pydantic.ValidationError. The executor catches
    it and surfaces a clean ToolError to the LLM so it can retry/adjust.
    """
    model = get_response_model(tool_name)
    if model is None:
        return data
    # Lists and nullable singletons are handled by their model's root type
    # via `RootModel` (see agenda.py). For plain BaseModel, pass dict.
    parsed = model.model_validate(data)
    return parsed.model_dump(mode="json", exclude_none=False)
